name: Next.js CI

on:
  push:
    branches: [main]
  
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  run-ci:
    uses: ./.github/workflows/reusable-next-ci.yml

    with:
      node-version: "24"

    secrets:
      clerk-publishable-key: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
      clerk-secret-key: ${{ secrets.CLERK_SECRET_KEY }}
